services:
  - type: web
    name: scholarship-system
    env: docker
    plan: free
    dockerCommand: "" # Uses CMD from Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false # You will provide the Internal Database URL from MediQ DB here
      - key: DB_PREFIX
        value: "scholarship_"
